class AuthError(Exception):
    pass


class BusyError(Exception):
    pass
